# -*- coding: utf-8 -*-
"""Battleship

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kte1m2XdmWzHPmf-LI9k7jAj_-8UdX1V
"""

""" Welcome to the 2 Player Battleship Game  """
""" You will gus coordinates until you destroy 5 ships, the first one to destroy the ships will win"""
player_1 = input("Print your name")
player_2 = input("Print your name")

1_ships = [A6, B6, C3]
2_ships = [G1, G2, G3]

class Player:





class Ship: